---
sidebar: sidebar 
permalink: reference_security_groups_windows_ad_servers.html 
keywords: Cloud Volumes Service for AWS, security groups, ports, protocols, Windows, Active Directory, AD 
summary: 'Wenn Sie Windows Active Directory (AD)-Server mit Cloud Volumes verwenden, sollten Sie sich mit den Anleitungen zu den Einstellungen der AWS-Sicherheitsgruppen vertraut machen. Die Einstellungen ermöglichen die korrekte Integration von Cloud Volumes mit AD.' 
---
= Einstellungen der AWS Sicherheitsgruppen für Windows AD Server
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Wenn Sie Windows Active Directory (AD)-Server mit Cloud Volumes verwenden, sollten Sie sich mit den Anleitungen zu den Einstellungen der AWS-Sicherheitsgruppen vertraut machen. Die Einstellungen ermöglichen die korrekte Integration von Cloud Volumes mit AD.

Standardmäßig enthält die AWS-Sicherheitsgruppe, die auf eine EC2 Windows-Instanz angewendet wird, keine eingehenden Regeln für ein Protokoll außer RDP. Sie müssen den Sicherheitsgruppen, die an jede Windows AD-Instanz angehängt sind, Regeln hinzufügen, um eingehende Kommunikation von Cloud Volumes Service zu aktivieren. Folgende Ports sind erforderlich:

[cols="40,30,30"]
|===
| Service | Port | Protokoll 


| AD Web Services | 9389 | TCP 


| DNS | 53 | TCP 


| DNS | 53 | UDP 


| ICMPv4 | K. A. | Echo Antwort 


| Kerberos | 464 | TCP 


| Kerberos | 464 | UDP 


| Kerberos | 88 | TCP 


| Kerberos | 88 | UDP 


| LDAP | 389 | TCP 


| LDAP | 389 | UDP 


| LDAP | 3268 | TCP 


| NetBIOS-Name | 138 | UDP 


| SAM/LSA | 445 | TCP 


| SAM/LSA | 445 | UDP 


| Sicheres LDAP | 636 | TCP 


| Sicheres LDAP | 3269 | TCP 


| W32mal | 123 | UDP 
|===
Wenn Sie Ihre AD-Installations-Domain-Controller und Mitgliedsserver auf einer AWS EC2-Instanz implementieren und managen, benötigen Sie mehrere Sicherheitsgruppenregeln, um den Datenverkehr für die Cloud Volumes Service zuzulassen. Im Folgenden finden Sie ein Beispiel zur Implementierung dieser Regeln für AD-Applikationen im Rahmen der AWS CloudFormation-Vorlage.

[source, json]
----
{
    "AWSTemplateFormatVersion" : "2010-09-09",
    "Description" : "Security Group for AD",
    "Parameters" :
    {
    	"VPC" :
    	{
    		"Type" : "AWS::EC2::VPC::Id",
    		"Description" : "VPC where the Security Group will belong:"
    	},
    	"Name" :
    	{
    		"Type" : "String",
    		"Description" : "Name Tag of the Security Group:"
    	},
    	"Description" :
    	{
    		"Type" : "String",
    		"Description" : "Description Tag of the Security Group:",
            "Default" : "Security Group for Active Directory for CVS "
    	},
        "CIDRrangeforTCPandUDP" :
    	{
    		"Type" : "String",
    		"Description" : "CIDR Range for the UDP ports 445,138,464,389,53,123 and for the TCP ports 464,339,3389,3268,88,636,9389,445 and 0-65535: *CIDR range format: 10.0.0.0/24"
    	}
    },
    "Resources" :
    {
    	"ADSGWest" :
    	{
    		"Type" : "AWS::EC2::SecurityGroup",
    		"Properties" :
    		{
    			"GroupDescription" : {"Ref" : "Description"},
    			"VpcId" : { "Ref" : "VPC" },
                "SecurityGroupIngress" : [
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "445",
                        "ToPort" : "445"
                    },
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "138",
                        "ToPort" : "138"
                    },
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "464",
                        "ToPort" : "464"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "464",
                        "ToPort" : "464"
                    },
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "389",
                        "ToPort" : "389"
                    },
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "53",
                        "ToPort" : "53"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "339",
                        "ToPort" : "339"
                    },
                    {
                        "IpProtocol" : "udp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "123",
                        "ToPort" : "123"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "3389",
                        "ToPort" : "3389"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "3268",
                        "ToPort" : "3268"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "88",
                        "ToPort" : "88"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "636",
                        "ToPort" : "636"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "3269",
                        "ToPort" : "3269"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "53",
                        "ToPort" : "53"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "0",
                        "ToPort" : "65535"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "9389",
                        "ToPort" : "9389"
                    },
                    {
                        "IpProtocol" : "tcp",
                        "CidrIp" : {"Ref" : "CIDRrangeforTCPandUDP"},
                        "FromPort" : "445",
                        "ToPort" : "445"
                    }
                ]
    		}
    	}
    },
    "Outputs" :
    {
        "SecurityGroupID" :
        {
            "Description" : "Security Group ID",
            "Value" : { "Ref" : "ADSGWest" }
        }
    }
}
----