---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: Wenn Sie verstehen, wie Cloud Volumes ONTAP standardmäßig konfiguriert ist, können Sie Ihre Systeme einrichten und verwalten. Dies gilt insbesondere, wenn Sie mit ONTAP vertraut sind, da sich das Standard-Setup für Cloud Volumes ONTAP von ONTAP unterscheidet. 
---
= Standardkonfiguration für Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie verstehen, wie Cloud Volumes ONTAP standardmäßig konfiguriert ist, können Sie Ihre Systeme einrichten und verwalten. Dies gilt insbesondere, wenn Sie mit ONTAP vertraut sind, da sich das Standard-Setup für Cloud Volumes ONTAP von ONTAP unterscheidet.



== Standardwerte

* Cloud Volumes ONTAP ist als Single-Node-System in AWS, Azure und GCP verfügbar und als HA-Paar in AWS und Azure.
* Cloud Manager erstellt bei der Implementierung von Cloud Volumes ONTAP eine Storage-VM mit Datenservice. Einige Konfigurationen unterstützen zusätzliche Storage VMs. link:task_managing_svms.html["Erfahren Sie mehr über das Management von Storage VMs"].
* Cloud Manager installiert die folgenden ONTAP Funktionslizenzen automatisch auf Cloud Volumes ONTAP:
+
** CIFS
** FlexCache
** FlexClone
** ISCSI
** NetApp Volume Encryption (nur für BYOL oder registrierte PAYGO Systeme)
** NFS
** SnapMirror
** SnapRestore
** SnapVault


* Standardmäßig werden mehrere Netzwerkschnittstellen erstellt:
+
** Eine Cluster Management-LIF
** Eine Intercluster-LIF
** SVM-Management-LIF auf HA-Systemen in Azure, Single-Node-Systeme in AWS und optional auf HA-Systemen in mehreren AWS Availability Zones
** Eine Node Management-LIF
** Eine iSCSI-Daten-LIF
** Eine CIFS- und NFS-Daten-LIF
+

NOTE: Aufgrund der EC2-Anforderungen ist das LIF-Failover für Cloud Volumes ONTAP standardmäßig deaktiviert. Durch die Migration einer LIF auf einen anderen Port wird die externe Zuordnung zwischen IP-Adressen und Netzwerkschnittstellen in der Instanz aufgehoben, sodass der LIF nicht mehr zugänglich ist.



* Cloud Volumes ONTAP sendet Konfigurations-Backups über HTTPS an den Connector.
+
Auf die Backups kann über zugegriffen werden https://ipaddress/occm/offboxconfig/[] Wobei _ipaddress_ die IP-Adresse des Connector-Hosts ist.

* Cloud Manager legt einige Volume-Attribute anders fest als andere Management-Tools (z. B. System Manager oder CLI).
+
In der folgenden Tabelle sind die Volume-Attribute aufgeführt, die Cloud Manager anders als die Standardeinstellungen festlegt:

+
[cols="15,85"]
|===
| Attribut | Vom Cloud Manager festgelegter Wert 


| AutoSize Modus | Wachsen 


| Maximale automatische Größe  a| 
1.000 Prozent


NOTE: Der Kontoadministrator kann diesen Wert auf der Seite Einstellungen ändern.



| Sicherheitsstil | NTFS für CIFS-Volumes UNIX für NFS-Volumes 


| Platz garantiert Stil | Keine 


| UNIX-Berechtigungen (nur NFS) | 777 
|===
+
Informationen zu diesen Attributen finden Sie auf der Seite „_Volume create_ man“.





== Boot- und Root-Daten für Cloud Volumes ONTAP

Zusätzlich zum Storage für Benutzerdaten erwirbt Cloud Manager auch Cloud Storage für Boot- und Root-Daten auf jedem Cloud Volumes ONTAP System.



=== AWS

* Zwei Festplatten pro Node für Boot- und Root-Daten:
+
** 9.7: 160-GB-io1-Festplatte für Boot-Daten und eine 220-GB-gp2-Festplatte für Stammdaten
** 9.6: 93-GB-io1-Festplatte für Boot-Daten und eine 140-GB-gp2-Festplatte für Stammdaten
** 9.5: 45-GB-io1-Festplatte für Boot-Daten und eine 140-GB-gp2-Festplatte für Stammdaten


* Ein EBS-Snapshot für jede Boot- und Root-Festplatte
* Bei HA-Paaren ist ein EBS-Volume für die Mediator-Instanz, das ca. 8 GB beträgt




=== Azure (Single Node)

* Drei Premium-SSD-Festplatten:
+
** Eine 10-GB-Festplatte für Boot-Daten
** Eine 140-GB-Festplatte für Stammdaten
** Eine 128-GB-Festplatte für NVRAM
+
Wenn die virtuelle Maschine, die Sie für Cloud Volumes ONTAP ausgewählt haben, Ultra-SSDs unterstützt, verwendet das System statt einer Premium-SSD eine Ultra-SSD für NVRAM.



* Eine 1024-GB-Standardfestplatte zum Speichern der Kerne
* Ein Azure Snapshot für jedes Boot- und Root-Laufwerk




=== Azure (HA-Paare)

* Zwei 10-GB-Premium-SSD-Laufwerke für das Boot-Volume (eine pro Node)
* Zwei Blobs für 140 GB Premium-Storage für das Root-Volume (eine pro Node)
* Zwei 1024-GB-Standard-HDD-Festplatten zum Speichern der Cores (eine pro Node)
* Zwei 128-GB-Premium-SSD-Festplatten für NVRAM (eine pro Node)
* Ein Azure Snapshot für jedes Boot- und Root-Laufwerk




=== GCP

* Eine persistente 10-GB-Standardfestplatte für Boot-Daten
* Eine persistente 64-GB-Standardfestplatte für Stammdaten
* Eine persistente 500-GB-Standardfestplatte für NVRAM
* Eine persistente 216-GB-Standardfestplatte zum Speichern der Kerne
* Je ein GCP-Snapshot für die Boot-Festplatte und die Root-Festplatte




=== Wo sich die Festplatten befinden

Cloud Manager legt den Storage wie folgt vor:

* Boot-Daten befinden sich auf einem Laufwerk, das mit der Instanz oder Virtual Machine verbunden ist.
+
Diese Festplatte, die das Boot-Image enthält, steht Cloud Volumes ONTAP nicht zur Verfügung.

* Die Stammdaten, die die Systemkonfiguration und die Protokolle enthalten, befinden sich in aggr0.
* Das Root-Volume der Storage Virtual Machine (SVM) befindet sich in aggr1.
* Daten-Volumes befinden sich auch in aggr1.




=== Verschlüsselung

Boot- und Root-Festplatten sind in Azure und Google Cloud Platform immer verschlüsselt, da bei diesen Cloud-Providern die Verschlüsselung standardmäßig aktiviert ist.

Wenn Sie die Datenverschlüsselung in AWS mithilfe des KMS (Key Management Service) aktivieren, werden sowohl Boot- als auch Root-Festplatten für Cloud Volumes ONTAP verschlüsselt. Dazu gehört die Boot-Festplatte für die Instanz des Mediators in einem HA-Paar. Die Laufwerke werden über das CMK verschlüsselt, das Sie bei der Erstellung der Arbeitsumgebung auswählen.
